environment:
  matrix:
    - NODE_VERSION: "4"
    - NODE_VERSION: "6"
    - NODE_VERSION: "8"

# Install scripts runs after repo cloning
install:
  - ps: Install-Product node $env:NODE_VERSION
  - npm install

# Post-install test scripts
test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build
build: off
